// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMS_backend;

#nullable disable

namespace SMS_backend.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20251211054225_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMS_backend.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Management",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "Research & Community Extension",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 3,
                            Name = "School Chaplain",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 4,
                            Name = "Human Resource Department",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 5,
                            Name = "Admission",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 6,
                            Name = "Academic Department",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 7,
                            Name = "Technical/Vocational (TechVoc) Program",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 8,
                            Name = "Guidance & Counseling",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 9,
                            Name = "Learning Resource Center (LRC)",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 10,
                            Name = "Student Affairs & Services Office (OSA)",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 11,
                            Name = "Pre-School / Elementary / Junior High School",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 12,
                            Name = "Preschool",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 13,
                            Name = "Elementary",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 14,
                            Name = "Junior High School (JHS)",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 15,
                            Name = "Senior High School (SHS)",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 16,
                            Name = "Grade 11",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 17,
                            Name = "Grade 12",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 18,
                            Name = "Administration Department",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 19,
                            Name = "ICT / Admin Officer",
                            RecordStatus = 1
                        });
                });

            modelBuilder.Entity("SMS_backend.Models.DepartmentLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("UpdaterID");

                    b.ToTable("DepartmentLogs");
                });

            modelBuilder.Entity("SMS_backend.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentID = 1,
                            Name = "School Director",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 2,
                            DepartmentID = 2,
                            Name = "Head",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 3,
                            DepartmentID = 3,
                            Name = "Chaplain",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 4,
                            DepartmentID = 4,
                            Name = "HR Dept Head",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 5,
                            DepartmentID = 5,
                            Name = "Admission & External Relations Officer",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 6,
                            DepartmentID = 6,
                            Name = "Registrar",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 7,
                            DepartmentID = 7,
                            Name = "TechVoc Program Head",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 8,
                            DepartmentID = 8,
                            Name = "Guidance & Counseling Center Head",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 9,
                            DepartmentID = 9,
                            Name = "Head",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 10,
                            DepartmentID = 10,
                            Name = "Head",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 11,
                            DepartmentID = 11,
                            Name = "Academic Head, Pre-School / JHS",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 12,
                            DepartmentID = 12,
                            Name = "Preschool Coordinator",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 13,
                            DepartmentID = 13,
                            Name = "Elementary Coordinator",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 14,
                            DepartmentID = 14,
                            Name = "JHS Coordinator",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 15,
                            DepartmentID = 15,
                            Name = "SHS Principal",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 16,
                            DepartmentID = 16,
                            Name = "Grade 11 Coordinator",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 17,
                            DepartmentID = 17,
                            Name = "Grade 12 Coordinator",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 18,
                            DepartmentID = 18,
                            Name = "Administration Dept Head",
                            RecordStatus = 1
                        },
                        new
                        {
                            ID = 19,
                            DepartmentID = 19,
                            Name = "ICT Admin Officer",
                            RecordStatus = 1
                        });
                });

            modelBuilder.Entity("SMS_backend.Models.PositionLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PositionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PositionID");

                    b.HasIndex("UpdaterID");

                    b.ToTable("PositionLogs");
                });

            modelBuilder.Entity("SMS_backend.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("SMS_backend.Models.RoleLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UpdaterID");

                    b.ToTable("RoleLog");
                });

            modelBuilder.Entity("SMS_backend.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SMS_backend.Models.UserLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UpdaterID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("SMS_backend.Models.UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignerID")
                        .HasColumnType("int");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AssignerID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SMS_backend.Models.UserRoleLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.Property<int?>("UserRoleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UpdaterID");

                    b.HasIndex("UserRoleID");

                    b.ToTable("UserRoleLogs");
                });

            modelBuilder.Entity("SMS_backend.Models.Department", b =>
                {
                    b.HasOne("SMS_backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS_backend.Models.DepartmentLog", b =>
                {
                    b.HasOne("SMS_backend.Models.Department", "Department")
                        .WithMany("DepartmentLogs")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("SMS_backend.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterID");

                    b.Navigation("Department");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("SMS_backend.Models.Position", b =>
                {
                    b.HasOne("SMS_backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID");

                    b.HasOne("SMS_backend.Models.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Creator");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SMS_backend.Models.PositionLog", b =>
                {
                    b.HasOne("SMS_backend.Models.Position", "Position")
                        .WithMany("PositionLogs")
                        .HasForeignKey("PositionID");

                    b.HasOne("SMS_backend.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterID");

                    b.Navigation("Position");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("SMS_backend.Models.Role", b =>
                {
                    b.HasOne("SMS_backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS_backend.Models.RoleLog", b =>
                {
                    b.HasOne("SMS_backend.Models.Role", "Role")
                        .WithMany("RoleLogs")
                        .HasForeignKey("RoleID");

                    b.HasOne("SMS_backend.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterID");

                    b.Navigation("Role");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("SMS_backend.Models.User", b =>
                {
                    b.HasOne("SMS_backend.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS_backend.Models.UserLog", b =>
                {
                    b.HasOne("SMS_backend.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterID");

                    b.HasOne("SMS_backend.Models.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserID");

                    b.Navigation("Updater");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMS_backend.Models.UserRole", b =>
                {
                    b.HasOne("SMS_backend.Models.User", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignerID");

                    b.HasOne("SMS_backend.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID");

                    b.HasOne("SMS_backend.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID");

                    b.Navigation("Assigner");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMS_backend.Models.UserRoleLog", b =>
                {
                    b.HasOne("SMS_backend.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterID");

                    b.HasOne("SMS_backend.Models.UserRole", "UserRole")
                        .WithMany("UserRoleLogs")
                        .HasForeignKey("UserRoleID");

                    b.Navigation("Updater");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("SMS_backend.Models.Department", b =>
                {
                    b.Navigation("DepartmentLogs");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("SMS_backend.Models.Position", b =>
                {
                    b.Navigation("PositionLogs");
                });

            modelBuilder.Entity("SMS_backend.Models.Role", b =>
                {
                    b.Navigation("RoleLogs");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SMS_backend.Models.User", b =>
                {
                    b.Navigation("UserLogs");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SMS_backend.Models.UserRole", b =>
                {
                    b.Navigation("UserRoleLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
